[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  MONGODB_URI = "mongodb+srv://premnarayani1682_db_user:Narayani1682@cluster0.2sbd00i.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
